const nama = 'Rani';
const nilaiTeks = '80';
const nilaiAngka = 80;
const nilaiangka = 85;
const nilaiangka1 = "80Number";
const aktif = true;
console.log(typeof nama);
console.log(typeof nilaiTeks);
console.log(typeof nilaiAngka);
console.log(typeof aktif);
console.log(nilaiTeks + 5);
console.log(Number(nilaiTeks) + 5);
console.log(nilaiTeks == nilaiAngka);
console.log(nilaiTeks === nilaiAngka);
console.log(nilaiangka === nilaiAngka);
console.log(Number(nama));
console.log(Number(nilaiangka1));